version: "3.8"

services:
  app:
    build: .
    container_name: odsfera_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html:cached
    environment:
      APP_ENV: dev
      DATABASE_URL: mysql://root:root@db:3306/odsfera_db
      DEFAULT_URI: http://localhost:8080
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: odsfera_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: odsfera_db
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"  # opcional
    restart: unless-stopped

volumes:
  db_data:
